name: Changelog Action
description: Automatically creates a changelog for Pull Requests

author: Conrad Großer <grosserconrad@gmail.com>

runs:
  using: "composite"
  steps:
    - name: Prettify code!
      shell: bash
      run: >-
        ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_HEAD_REF: ${{ github.head_ref }}
        INPUT_BASE_REF: ${{ github.base_ref }}

branding:
  icon: "activity"
  color: "green"
